# 开发环境
# YAML 语言
# 一种简洁的非标记语言，以数据为中心，使用空格，缩进，分行组织数据，从而使得表示更加简洁易读
# 语法格式：
# 1.标准格式：键值对的形式， key:(空格)value
# 2.使用空格代表层级关系，以 “:” 结束

# 注意：当yml与properties文件同时存在时，配置优先以properties为主


#Server
server:
  port: 8888

#dataSource

#debug
debug: false