server:
  port: 8888
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      # 单个文件最大尺寸
      max-file-size: 2MB
      # 一个请求最大尺寸
      max-request-size: 50MB
      # 临时文件
            #location: d:/temp
  mvc:
    date-format: yyyy-MM-dd
    # 配置静态资源访问前缀(不配置的话，在访问static下静态资源404)
    static-path-pattern: /static/**


# 上传文件归档目录
app:
  upload:
    location: E:/workspace/SpringBoot-Modules-Study/springboot-Day5/uploaded/