server:
  port: 8888
debug: false

spring:

  # json 输出格式化与时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss SSS
    time-zone: GMT+8
    serialization:
      indent-output: true
  mvc:
    date-format: yyyy-MM-dd
  # console 控制台打印字体彩色输出
  output:
    ansi:
      enabled: ALWAYS
  # datasource
  datasource:
      druid:
        url: jdbc:mysql://localhost:3306/scott?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver

        # druid
        # 数据库类型为mysql
        db-type: mysql
        # 启动时初始化5个连接
        initialSize: 5
        # 最小空闲连接5个
        min-idle: 5
        # 最大连接数量20
        max-active: 20
        # 获取连接等待时间60秒，超出报错
        max-wait: 60000
        # 每60秒执行一次连接回收器
        time-between-eviction-runs-millis: 60000
        # 5分钟内没有任何操作的空闲连接会被回收
        min-evictable-idle-time-millis: 300000
        # 验证连接有效性的SQL
        validation-query: select 'x'
        # 空闲时校验，建议开启
        test-while-idle: true
        # 使用中是否校验有效性，推荐关闭
        test-on-borrow: false
        # 归还连接时校验有效性，推荐关闭
        test-on-return: false
        # oracle 推荐使用
        pool-prepared-statements: false
        # 设置过滤器，stat用于接收状态，wall用于防止SQL注入,logback则说明使用logback日志输出
        filters: stat,wall

        filter:
          stat:
            enabled: true
            db-type: mysql
            log-slow-sql: true
            slow-sql-millis: 2000
          wall:
            enabled: true
            db-type: mysql
            config.delete-allow: false
            config.drop-table-allow: false

# mybatis
mybatis:
  # 核心配置文件，指定的是mybatis-config.xml
  config-location: classpath:/mybatis/mybatis-config.xml
  # 指定mapper映射文件,全注解方式不需要
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml

# 打印sql
logging:
  level:
     cn.gcheng.springboot.mapper : debug

