server:
  port: 8888
debug: false

spring:
  # json 输出格式化与时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss SSS
    time-zone: GMT+8
    serialization:
      indent-output: true
  mvc:
    static-path-pattern: /static/**