server:
  port: 8888
debug: false



spring:
  # \u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scott?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  # json \u8F93\u51FA\u683C\u5F0F\u5316\u4E0E\u65F6\u95F4\u683C\u5F0F\u5316
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss SSS
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd

# mybatis
mybatis:
  # \u6838\u5FC3\u914D\u7F6E\u6587\u4EF6\uFF0C\u6307\u5B9A\u7684\u662Fmybatis-config.xml
  config-location: classpath:/mybatis/mybatis-config.xml
  # \u6307\u5B9Amapper\u6620\u5C04\u6587\u4EF6,\u5168\u6CE8\u89E3\u65B9\u5F0F\u4E0D\u9700\u8981
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
